Failure # 1 (occurred at 2023-12-01_18-06-10)
The actor died because of an error raised in its creation task, [36mray::PPO.__init__()[39m (pid=10084, ip=127.0.0.1, actor_id=7ca33c4227872a9a7729996001000000, repr=PPO)
  File "/Users/anubhavjangra/Library/Python/3.9/lib/python/site-packages/ray/rllib/evaluation/worker_set.py", line 227, in _setup
    self.add_workers(
  File "/Users/anubhavjangra/Library/Python/3.9/lib/python/site-packages/ray/rllib/evaluation/worker_set.py", line 593, in add_workers
    raise result.get()
  File "/Users/anubhavjangra/Library/Python/3.9/lib/python/site-packages/ray/rllib/utils/actor_manager.py", line 481, in __fetch_result
    result = ray.get(r)
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, [36mray::RolloutWorker.__init__()[39m (pid=10089, ip=127.0.0.1, actor_id=db19ed3012ef6566e9bb561e01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x16a62f1f0>)
  File "/Users/anubhavjangra/Library/Python/3.9/lib/python/site-packages/ray/rllib/evaluation/rollout_worker.py", line 397, in __init__
    self.env = env_creator(copy.deepcopy(self.env_context))
  File "/Users/anubhavjangra/columbia/courses/coms4444/project4/Wedding-Gossip/Wedding-Gossip-Environment/train_model.py", line 29, in <lambda>
    register_env(env_name, lambda config: ParallelPettingZooEnv(env_creator(config)))
  File "/Users/anubhavjangra/columbia/courses/coms4444/project4/Wedding-Gossip/Wedding-Gossip-Environment/train_model.py", line 18, in env_creator
    env = WeddingGossipEnvironment()
NameError: name 'WeddingGossipEnvironment' is not defined

During handling of the above exception, another exception occurred:

[36mray::PPO.__init__()[39m (pid=10084, ip=127.0.0.1, actor_id=7ca33c4227872a9a7729996001000000, repr=PPO)
  File "/Users/anubhavjangra/Library/Python/3.9/lib/python/site-packages/ray/rllib/algorithms/algorithm.py", line 517, in __init__
    super().__init__(
  File "/Users/anubhavjangra/Library/Python/3.9/lib/python/site-packages/ray/tune/trainable/trainable.py", line 161, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/Users/anubhavjangra/Library/Python/3.9/lib/python/site-packages/ray/rllib/algorithms/algorithm.py", line 639, in setup
    self.workers = WorkerSet(
  File "/Users/anubhavjangra/Library/Python/3.9/lib/python/site-packages/ray/rllib/evaluation/worker_set.py", line 179, in __init__
    raise e.args[0].args[2]
NameError: name 'WeddingGossipEnvironment' is not defined
